# Generated by Django 5.0.2 on 2024-02-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_fournisseur_produit_fornisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitsNC',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magasin.produit')),
                ('Dugree_garantie', models.CharField(max_length=100)),
            ],
            bases=('magasin.produit',),
        ),
    ]
